# Etapa 1: Construir o aplicativo
FROM node:16-alpine as build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build --prod

# Etapa 2: Servir o aplicativo com Nginx
FROM nginx:alpine

COPY --from=build /app/dist/virtualfilesystem-frontend /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
