# Use uma imagem base com Java
FROM openjdk:17-jdk-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia o jar construído para o contêiner
COPY target/virtualfilesystem-0.0.1-SNAPSHOT.jar app.jar

# Expor a porta que o aplicativo usará
EXPOSE 8080

# Comando para executar o aplicativo
ENTRYPOINT ["java","-jar","app.jar"]
